name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: papermill-kubeflow
        auto-update-conda: true
        auto-activate-base: false
    - name: Setup Papermill
      shell: bash -l {0}
      run: |
        conda info
        conda install pip
        conda install jupyter
        conda install ipykernel
        python -m ipykernel install --user --name papermill-kubeflow --display-name "papermill-kubeflow"
        pip install papermill
        echo "::add-path::$(dirname $(which papermill))"

    - name: Build from source
      run: |
        npm install
        npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: papermill-kubeflow
        auto-update-conda: true
        auto-activate-base: false

    - name: Setup Papermill
      shell: bash -l {0}
      run: |
        conda info
        conda install pip
        conda install jupyter
        conda install ipykernel
        python -m ipykernel install --user --name papermill-kubeflow --display-name "papermill-kubeflow"
        pip install papermill
        echo "::add-path::$(dirname $(which papermill))"

    - name: Test Action locally
      uses: ./
      with:
        input: test/data/sample-nb-1.ipynb
        output: test/build/sample-nb-1-output.ipynb
